#!/usr/bin/expect

set LOGFILE /var/log/inst-spy-fake.log
#set LOGFILE /var/log/xrm_epics.log
set log [open $LOGFILE  w]
foreach name [array names ::env] {
	puts $log "$name $::env($name)"
}
close $log

set mkey $::env(REDIS_MKEY)
# count is a proxy for timestamp
set count 1     
while { 1 } {
	gets stdin ib
	set rsp "$mkey:[format "%08d" $count] $ib"
	puts $rsp
	flush stdout
	incr count
}
